# Generated by Django 6.0.4 on 2026-04-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_mode",
                    models.CharField(
                        choices=[("manual", "Manual Input"), ("upload", "File Upload")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="assessments/%Y/%m/%d/"
                    ),
                ),
                ("risk_score", models.FloatField(default=0, help_text="0-100 scale")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low (0-30)"),
                            ("Moderate", "Moderate (31-55)"),
                            ("High", "High (56-75)"),
                            ("Critical", "Critical (76-100)"),
                        ],
                        default="Low",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_explanation", models.TextField()),
                ("threat_scenarios", models.JSONField(default=list)),
                ("remediation_steps", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("model_used", models.CharField(default="gemini-pro", max_length=100)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_output",
                        to="grc.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KRIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kri_name", models.CharField(max_length=255)),
                ("raw_value", models.FloatField()),
                (
                    "normalized_score",
                    models.FloatField(help_text="0-100 normalized value"),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("Safe", "Safe (Green)"),
                            ("Watch", "Watch (Amber)"),
                            ("Warning", "Warning (Orange)"),
                            ("Critical", "Critical (Red)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("weight", models.FloatField(default=1.0)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kri_records",
                        to="grc.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-normalized_score"],
            },
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Fintech", "Fintech"),
                            ("Banking", "Banking"),
                            ("Telecom", "Telecom"),
                            ("Government", "Government"),
                            ("IT", "IT / Corporate"),
                        ],
                        default="Fintech",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(default="1.0", max_length=50)),
                ("description", models.TextField(default="")),
                ("source_url", models.URLField(blank=True, null=True)),
                ("rules", models.JSONField(default=dict)),
                ("last_fetched", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["sector", "name"],
                "unique_together": {("sector", "name")},
            },
        ),
        migrations.CreateModel(
            name="RegulationDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Fintech", "Fintech"),
                            ("Banking", "Banking"),
                            ("Telecom", "Telecom"),
                            ("Government", "Government"),
                            ("IT", "IT / Corporate"),
                        ],
                        max_length=100,
                    ),
                ),
                ("regulation_name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("source_url", models.URLField()),
                ("content", models.TextField()),
                ("last_fetched", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("sector", "regulation_name", "version")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Compliant", "Compliant"),
                            ("Partial", "Partial"),
                            ("Non-Compliant", "Non-Compliant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("violated_kri_names", models.JSONField(default=list)),
                ("clause_reference", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_results",
                        to="grc.assessment",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grc.regulation"
                    ),
                ),
            ],
            options={
                "ordering": ["status", "regulation__name"],
                "unique_together": {("assessment", "regulation")},
            },
        ),
    ]
