# Generated by Django 6.0.4 on 2026-05-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aioutput',
            name='compliance_proof',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='compliance_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='exploitability_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='impact_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='likelihood_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='residual_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='High', max_length=20)),
                ('required_evidence', models.TextField(blank=True)),
                ('remediation_guidance', models.TextField(blank=True)),
                ('mapped_kri_name', models.CharField(blank=True, max_length=100)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='grc.regulation')),
            ],
        ),
        migrations.CreateModel(
            name='ControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Compliant', 'Compliant'), ('Partial', 'Partial'), ('Non-Compliant', 'Non-Compliant')], max_length=20)),
                ('evidence', models.TextField()),
                ('ai_analysis', models.TextField()),
                ('risk_impact', models.CharField(max_length=20)),
                ('confidence_score', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_results', to='grc.assessment')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.control')),
            ],
        ),
    ]
